import matplotlib
import seaborn as sns

# define models palette
model_label_map = {
    "VGG16_VGGFace2_128": "face identification (VGGFace2)",
    "VGG16_ImageNet_128": "object classification (ImageNet)",
    "VGG16_BFM_128": "inverse rendering (BFM)",
    "VGG16_VGGFace2_VAE_encoder_128": "autoencoding (VGGFace2)",
    "VGG16_BFM_VAE_encoder_128": "autoencoding (BFM)",
    "VGG16_BFM_identity_128": "face identification (BFM)",
    "leave1out": "leave one subject out",
    "BFM": "BFM latents",
}
model_abbrev_map = {
    "VGG16_VGGFace2_128": "faceID-VGGFace2",
    "VGG16_ImageNet_128": "objCat-ImageNet",
    "VGG16_BFM_128": "invRend-BFM",
    "VGG16_VGGFace2_VAE_encoder_128": "autoenc-VGGFace2",
    "VGG16_BFM_VAE_encoder_128": "autoenc-BFM",
    "VGG16_BFM_identity_128": "faceID-BFM",
    "leave1out": "noise ceiling",
}
model_order = [
    "VGG16_BFM_128",
    "VGG16_ImageNet_128",
    "VGG16_VGGFace2_128",
    "VGG16_BFM_identity_128",
    "VGG16_VGGFace2_VAE_encoder_128",
    "VGG16_BFM_VAE_encoder_128",
    "leave1out",
]
model_palette = {
    "VGG16_VGGFace2_128": sns.color_palette("deep")[0],
    "VGG16_BFM_identity_128": sns.color_palette("deep")[-1],
    "VGG16_ImageNet_128": sns.color_palette("deep")[4],
    "VGG16_BFM_128": sns.color_palette("deep")[2],
    "VGG16_VGGFace2_VAE_encoder_128": sns.color_palette("colorblind")[1],
    "VGG16_BFM_VAE_encoder_128": sns.color_palette("bright")[-2],
    "leave1out": "gray",
    "BFM": sns.color_palette()[6],
}

stimulus_set_palette = {
    "controversial": "#d95f02",
    "controversial-144": "#d95f02",
    "controversial-72": "#d95f02",
    "systematic": "#1b9e77",
    "random": "#7570b3",
    "full": "#d95f02",
    "single_instance": "#ff0000",
    "only_shape": "#770000",
    "only_texture": "#ff0000",
    "no_diminishing_returns": "#ff0000",
}

stimulus_condition_title_map = {
    "random": "randomly\nsampled stimuli",
    "systematic": "systematically\nsampled stimuli",
    "controversial": "controversial\nstimuli",
}


def set_matplotlib_defaults():
    matplotlib.rcParams.update(
        {
            "font.size": 10,
            "font.family": "sans-serif",
            "font.sans-serif": "Arial",
            "text.usetex": False,
            "axes.linewidth": 0.5,
            "xtick.major.width": 0.5,
            "ytick.major.width": 0.5,
            "xtick.minor.width": 0.5,
            "ytick.minor.width": 0.5,
            # make the ticks shorter:
            "xtick.major.size": 2.0,
            "ytick.major.size": 2.0,
            "mathtext.fontset": "custom",
            "mathtext.it": "Arial:italic",
            "mathtext.rm": "Arial",
        }
    )


layer_names = {
    "VGG16_VGGFace2_128": [
        "conv1_1",
        "conv1_2",
        "conv2_1",
        "conv2_2",
        "conv3_1",
        "conv3_2",
        "conv3_3",
        "conv4_1",
        "conv4_2",
        "conv4_3",
        "conv5_1",
        "conv5_2",
        "conv5_3",
        "fc_6",
        "fc_7",
        "fc_8",
    ],
    "VGG16_BFM_identity_128": [
        "conv1_1",
        "conv1_2",
        "conv2_1",
        "conv2_2",
        "conv3_1",
        "conv3_2",
        "conv3_3",
        "conv4_1",
        "conv4_2",
        "conv4_3",
        "conv5_1",
        "conv5_2",
        "conv5_3",
        "fc_6",
        "fc_7",
        "fc_8",
    ],
    "VGG16_ImageNet_128": [
        "conv1_1",
        "conv1_2",
        "conv2_1",
        "conv2_2",
        "conv3_1",
        "conv3_2",
        "conv3_3",
        "conv4_1",
        "conv4_2",
        "conv4_3",
        "conv5_1",
        "conv5_2",
        "conv5_3",
        "fc_6",
        "fc_7",
        "fc_8",
    ],
    "VGG16_BFM_128": [
        "conv1_1",
        "conv1_2",
        "conv2_1",
        "conv2_2",
        "conv3_1",
        "conv3_2",
        "conv3_3",
        "conv4_1",
        "conv4_2",
        "conv4_3",
        "conv5_1",
        "conv5_2",
        "conv5_3",
        "fc_6",
        "fc_7",
        "fc_8",
    ],
    "VGG16_VGGFace2_VAE_encoder_128": [
        "conv1_1",
        "conv1_2",
        "conv2_1",
        "conv2_2",
        "conv3_1",
        "conv3_2",
        "conv3_3",
        "conv4_1",
        "conv4_2",
        "conv4_3",
        "conv5_1",
        "conv5_2",
        "conv5_3",
        "fc_6",
        "fc_7",
        "fc_8",
    ],
    "VGG16_BFM_VAE_encoder_128": [
        "conv1_1",
        "conv1_2",
        "conv2_1",
        "conv2_2",
        "conv3_1",
        "conv3_2",
        "conv3_3",
        "conv4_1",
        "conv4_2",
        "conv4_3",
        "conv5_1",
        "conv5_2",
        "conv5_3",
        "fc_6",
        "fc_7",
        "fc_8",
    ],
}
